name: thank_you
description: A new minimilstic mobile donation tracker.
publish_to: 'App Store and Play Store'

version: 1.0.4+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_speed_dial: ^4.1.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  bottom_bar: ^1.2.4
#  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  introduction_screen: ^2.1.0
  image_picker: ^0.8.4+4
  permission_handler: ^8.3.0
  path: ^1.8.0
  url_launcher: ^6.0.17
#  keyboard_actions: ^3.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: '#ffffff'
  image: assets/circleIcon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
      - family: CustomIcon
        fonts:
        - asset: assets/CustomIcon.ttf