name: thank_you
description: A new minimilstic mobile donation tracker.
publish_to: 'App Store and Play Store'

version: 1.0.6+9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_speed_dial: ^6.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  bottom_bar: ^2.0.2
#  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  introduction_screen: ^3.0.2
  image_picker: ^0.8.4+4
  permission_handler: ^10.0.0
  path: ^1.8.0
  url_launcher: ^6.0.17
  universal_io: ^2.0.4
  pdf: ^3.8.1
  share_plus: ^4.0.9
  csv: ^5.0.1
#  keyboard_actions: ^3.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  flutter_native_splash: ^2.2.5

flutter_native_splash:
  color: '#ffffff'
  image: assets/circleIcon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
      - family: CustomIcon
        fonts:
        - asset: assets/CustomIcon.ttf